### ISSUE TITLE
Node 18

### ISSUE THREAD

**Issue by Becker2273** [homebridge/homebridge-syno-spk#107]
Hi, Synology offers now a Node 18 Package on the Download site

**Comment by danray66** [comment]
Hi, Does it mean that we can update the node in any ways or we need to wait for a new release (3.0.10)?

**Comment by Lling** [comment]
We have to wait.

**Comment by Becker2273** [comment]
It seems that we have to wait. The message that Synology does not support the new version is still coming

Am 01.12.2022 um 16:34 schrieb danray66 ***@***.***>:

﻿

Hi, Does it mean that we can update the node in any ways or we need to wait for a new release (3.0.10)?

**Comment by sercontri** [comment]
Hello everyone! Is there an option to be able to update the Node.js from the terminal configuration within the homebridge app for Synology?

**Comment by johnnygoodface** [comment]
@sercontri 
Sure: _hb-service update-node_ (which updates to the latest available version of Node.js)
And if you wanna specify a version: _hb-service update-node 16.18.1_ (for example)

**Comment by Lling** [comment]
Yeah but it doesn‘t work at he moment.
You get the message, that dsm 7 doesn’t support node v18 at the moment (even if there is a official download for it)

**Comment by johnnygoodface** [comment]
Yes I know, that why I showed also how to install a "pre-18" version with hb-service update-node 16.18.1
At least this way you can update to the latest 16 version until the 18 is available.

**Comment by dppeak** [comment]
Any updates on this?

**Comment by johnnygoodface** [comment]
Node.js v18 (Version: 18.12.0-0005) is now available on Synology download center ([https://www.synology.com/en-id/releaseNote/Node.js_v18?model=DS420%2B](url)) but I'd wait a couple of weeks for the next iteration since it's the first release
![Screenshot 2022-12-28 at 11 06 04 AM](https://user-images.githubusercontent.com/24813857/209840039-4ad24947-f2f3-4d84-8a79-c48f55f3461d.jpg)

**Comment by Segelmichel** [comment]
When will homebridge recognize the availability of version 18? I'm desperately waiting to update ...

**Comment by sercontri** [comment]
We're still the same, right? I have tried to update from the terminal even by forcing the version and it continues to give me the error of not being supported.

**Comment by gamma** [comment]
Yes, I edited out the restriction - which did not really help due to GLIBC issues, and then checked which node it was using. I found a fat binary which I moved away and linked the system node 18.12 into place - that made it.

**Comment by dppeak** [comment]
Is this package repo no longer being maintained?

**Comment by pserbanp** [comment]
Is development  for this dropped? @oznu

**Comment by IngmarStein** [comment]
https://www.synology.com/en-us/DSM72 (currently in Beta) comes with Node 18.12.1

**Comment by dppeak** [comment]
Commenting to make sure this doesn't get closed.

**Comment by adamlilley88** [comment]
Are we still waiting for an update to sort this?

**Comment by NorthernMan54** [comment]
Folks, Oznu is off with other commitments, but the the rest of the collaborators are available.  So if the community has a pull request to submit we can accommodate.

**Comment by adamlilley88** [comment]
Not complete. Issue still present
