### ISSUE TITLE
mDNS advertising does not work

### ISSUE THREAD

**Issue by bpeck** [homebridge/homebridge-syno-spk#116]
Hello, I recently installed Homebridge via the synology package. Homebridge and it's UI work fine on my Synology as far as I can tell:
`Homebridge v1.6.0 (HAP v0.11.0)`

However, I cannot seem to add Homebridge as an accessory to my Home in iOS. I tried using the Discovery app, and do not see Homebrdige advertising anything under `_hap._udp`.

I also see that Homebridge lists in the status widget that it is using the wrong interface-- I have specified eth0, but in the status widget it lists the interface for a VPN connection, tun0.

Any ideas on how to get Homebridge to use the correct network interface?  I'm guessing thats why I don't see anything in the Discovery iOS app being advertised on my local network. I've tried using Ciao and the legacy HAP advertiser. I've tried restarting the NAS, having my iOS 16.2 device leave and rejoin the network.

Here is the config I've been trying to use:

```
{
    "bridge": {
        "name": "Homebridge 0847",
        "username": "0E:F3:28:24:5E:32",
        "port": 51604,
        "pin": redacted,
        "mdns": {
            "interface": redacted (its the local local LAN IP of my NAS)
        },
        "advertiser": "ciao",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Comment by Rappelsack** [comment]
I guess its the same here. In the UI there is the second point: Homebridge starting... and its all the time turning.
The homebridge didn't start.
In the logs there is this point: Could not create mDNS advertisement. The HAP-Server won't be discoverable: Error: No such interface found

**Comment by MSDaytona** [comment]
Is your Synology box compatible ? 
These are the compatible Sync NAS:
x86_64 - All 64 bit Intel / AMD CPU Models
evansport (i686) - DS214play, DS414play, DS415play
rtd1296 (armv8) - DS420j, DS220j, RS819, DS418, DS218, DS218play, DS118
armada37xx (armv8) - DS120j, DS119j
armada38x (armv7) - DS419slim, DS218j, RS217, RS816, DS416j, DS416slim, DS216, DS216j, DS116
alpine (armv7) - DS1817, DS1517, DS416, DS2015xs, DS1515, DS715, DS215+

Mine isn't ( I have a DS218+ ). I can install Homebridge but not pair with HomeKit.

**Comment by bpeck** [comment]
I also have a DS218+. This unit uses an intel celeron CPU though, so shouldn't it be compatible? It uses the x86 instruction set... Thanks for the heads up that you're also seeing this with this box,

**Comment by DIY-Bastler** [comment]
I also had this issue with my DS918, for me changing the mDNS advertiser to ciao as described [here](https://github.com/oznu/homebridge-syno-spk/issues/108#issuecomment-1328349391) helped.
