### ISSUE TITLE
Cannot update Node.js to 18.13

### ISSUE THREAD

**Issue by elmerindrawan** [homebridge/homebridge-syno-spk#117]
Used terminal in Homebridge, ran “hb-service update-node”. Returned “DSM 7 does not support Node.js 18 or later.” I have V18 installed via Synology package center.

**Comment by elmerindrawan** [comment]
Had an issue saying Node.js 16.16 was out of date. Appended the above command with “ hb-service update-node 16.19” and it updated and the warning went away. This should be good for now, but still need V18 support eventually.

**Comment by lukenukemmp3** [comment]
The error still persists.

**Comment by jwebbstevens** [comment]
```The plugin "homebridge-wemo" requires Node.js version of ^14.20.1 || ^16.18.0 || ^18.11.0 which does not satisfy the current Node.js version of v16.16.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF```

I have the same problem running on:

- DSM 7.1.1-42962 Update 4
- DS1520+
- INTEL Celeron J4125

**Comment by jwebbstevens** [comment]
I used the command ```hb-service update-node 16.19```` in the terminal window of _Homebridge_ and then restarted _Homebridge_ but it looks like it doesn't support going beyond Node.js version 16.

<img width="657" alt="Screenshot 2023-02-27 at 2 41 26 PM" src="https://user-images.githubusercontent.com/7277574/221666300-323d4cdd-7f32-47dd-b857-dd2007011506.png">

**Comment by primovist** [comment]
> I used the command ```hb-service update-node 16.19```` in the terminal window of _Homebridge_ and then restarted _Homebridge_ but it looks like it doesn't support going beyond Node.js version 16.
> 
> 
> 
> <img width="657" alt="Screenshot 2023-02-27 at 2 41 26 PM" src="https://user-images.githubusercontent.com/7277574/221666300-323d4cdd-7f32-47dd-b857-dd2007011506.png">
> 
> 
> 
> 
#120

**Comment by primovist** [comment]
#120

**Comment by jwebbstevens** [comment]
interesting. thanks @primovist
